#服务注册中心端口号
server:
  port: 4001

spring:
  application:
    name: topcheer-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gavenwangcn/springcloudconfig.git
          search-paths: respo

#服务注册中心实例的主机名、端口
eureka:
  prot: 1025
  instance:
    #将IP注册到Eureka Server上
    prefer-ip-address: true
    #Eureka Client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 5
    #续约到期时间
    lease-expiration-duration-in-seconds: 20
    hostname: localhost
  client:
    serviceUrl:
      #设置Eureka Server所在的地址
      defaultZone: http://${eureka.instance.hostname}:${eureka.prot}/eureka/
    #表示是否将自己注册在Eureka Server上
    register-with-eureka: true
    #表示是否从Eureka Server上获取注册信息
    fetch-registry: false
    #表示Eureka Client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 10
